taxi_co2:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: C:/Users/elain/OneDrive/Documents/DS/Systems II/ds3022-data-project-1/emissions.duckdb
      schema: main
      threads: 4
      keepalives_idle: 0
      search_path: main
