version: 2

sources:
  - name: nyc_taxi
    schema: main
    tables:
      - name: yellow_tripdata_full
      - name: green_tripdata_full
      - name: vehicle_emissions
      - name: yellow_tripdata_2024
      - name: green_tripdata_2024